import { Grid } from "@mui/material";
import Head from "next/head";
import Header from "../components/Header/Header";
import HotProducts from "../components/HotProducts/HotProducts";
import Layout from "../components/Layout/Layout";
import { CustomContainer } from "../components/Layout/LayoutStyle";
import OfferCard from "../components/OfferCard/OfferCard";
import LatestBlog from "../components/LatestBlog/LatestBlog";
import Footer from "../components/Footer/Footer";

export default function Home({ special, products, latestBlog }) {
  return (
    <div>
      <Head>
        <title>next_store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Layout>
        <CustomContainer>
          <Grid container spacing={2}>
            {special.map((item) => (
              <Grid item xs={12} sm={6} md={4} key={item.id}>
                <OfferCard item={item} />
              </Grid>
            ))}
          </Grid>
        </CustomContainer>
      </Layout>
      <HotProducts products={products} />
      <LatestBlog latestBlog={latestBlog} />
      <Footer />
    </div>
  );
}

export async function getStaticProps() {
  const specialRes = await fetch(
    "https://api.npoint.io/b26ab1faa1fc63f27d5d/special"
  );
  const special = await specialRes.json();

  const productsRes = await fetch(
    "https://api.npoint.io/b26ab1faa1fc63f27d5d/HotProducts"
  );
  const products = await productsRes.json();

  const latestBlogRes = await fetch(
    "https://api.npoint.io/b26ab1faa1fc63f27d5d/latestBlog"
  );
  const latestBlog = await latestBlogRes.json();
  return {
    props: { special, products, latestBlog }, // will be passed to the page component as props
  };
}